system_appdata_uid: 875
system_appdata_gid: 875

mosquitto_uid: 1883
mosquitto_gid: 1883

# Automate

automate_apps_dir: "/opt/automate"
automate_appdata_dir: "{{ automate_apps_dir }}/appdata"
automate_fragments_dir: "{{ automate_apps_dir }}/fragments"

docker_net_automate: "172.30.174.0/24"

homeassistant_config_key_path: "/home/homeassistant/.ssh/github_rsa"
homeassistant_container_config_path: "/config"

openzwave_mqtt_server: "mqtt.{{ domain_name }}"
openzwave_mqtt_port: 8883
openzwave_mqtt_tls: "true"
openzwave_usb_path: "/dev/zwave"

rclone_gce_key: "GCS"

# Public

public_apps_dir: "/opt/public"
public_appdata_dir: "{{ public_apps_dir }}/appdata"
public_fragments_dir: "{{ public_apps_dir }}/fragments"

public_external_networks: ["automate"]

docker_net_public: "172.30.170.0/24"
docker_net_glances: "172.30.172.0/24"
