- name: "Create user"
  register: "radarr_user"
  ansible.builtin.user:
    append: false
    create_home: false
    group: "{{ radarr.group | default(omit) }}"
    groups: "{{ radarr.extra_groups | default([]) | map(attribute = 'name') | join(',') }}"
    name: "radarr"
    shell: "/usr/bin/nologin"
    state: "present"
    system: true

- name: "Create config directories"
  loop:
    - { path: "" }
    - { path: "custom-cont-init.d" }
  ansible.builtin.file:
    <<: &owner_group
      owner: "{{ radarr_user.name }}"
      group: "{{ radarr.group | default(radarr_user.name) }}"
    path: "{{ radarr.config_dir }}/{{ item.path }}"
    state: "directory"
    mode: 0750

- name: "Create data directories"
  ansible.builtin.file:
    <<: *owner_group
    group: "{{ radarr.movies_group | default(radarr.group | default(radarr_user.name)) }}"
    path: "{{ radarr.movies_dir }}"
    state: "directory"
    mode: 0750

- name: "Add supplementary group support"
  ansible.builtin.copy:
    <<: *owner_group
    src: "extra_groups.sh"
    dest: "{{ radarr.config_dir }}/custom-cont-init.d/extra_groups.sh"
    mode: 0640

- name: "Create service fragment"
  include_role:
    name: "container"
    tasks_from: "service-fragment"
  vars:
    default_fragment:
      name: "radarr"
      definition:
        image: "ghcr.io/linuxserver/radarr:latest"
        environment:
          TZ: "{{ timezone }}"
          PUID: "{{ radarr_user.uid }}"
          PGID: "{{ radarr_user.group }}"
          EXTRA_GID: "{{ radarr.extra_groups | default([]) | map(attribute = 'gid') | join(' ') }}"
          UMASK_SET: "027"
        labels:
          traefik.http.services.radarr.loadbalancer.server.port: 7878
        restart: "unless-stopped"
        volumes:
          - "{{ radarr.config_dir }}:/config"
          - "{{ radarr.downloads_dir }}:/downloads:ro"
          - "{{ radarr.movies_dir }}:/movies"
    fragment: |
      {{
        default_fragment
          | combine(radarr.fragment | default({}), recursive=True, list_merge='append_rp')
          | to_json
      }}
