- name: "Create service fragment"
  include_role:
    name: "container"
    tasks_from: "service-fragment"
  vars:
    default_fragment:
      name: "glances"
      definition:
        image: "nicolargo/glances:3.1.6"
        environment:
          TZ: "{{ timezone }}"
          GLANCES_OPT: "-w --enable-plugin sensors"
        pid: "host"
        restart: "unless-stopped"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
    default_fragment_with_proxy:
      proxy:
        port: 61208
    fragment: |
      {{
        default_fragment
          | combine(default_fragment_with_proxy if glances.fragment.proxy is mapping else {}, recursive=True, list_merge='append_rp')
          | combine(glances.fragment | default({}), recursive=True, list_merge='append_rp')
          | to_json
      }}
