# Inventory: PRODUCTION
# Server: Avatar-Media

ansible_host: avatar-media-ansible

ssh_port: "{{ network.servers.media.ports.ssh }}"
internal_ip: "{{ network.servers.media.ip }}"
internal_hostname: "{{ network.servers.media.host }}"

minecraft_version: "1.15.2"

wan_if: "enp6s0"

traefik:
  entrypoints:
    trusted_ips:
      - "{{ network.servers.automate.ip }}/32"
