# Inventory: PRODUCTION
# Server: Avatar-Media

# Host
ansible_host: "avatar-media-ansible"

ssh_port: "{{ network.servers.media.ports.ssh }}"
internal_ip: "{{ network.servers.media.ip }}"
internal_hostname: "{{ network.servers.media.host }}"

tcp_ports: [ 80 ]

# Directories and mount points
data_mount: "/data"
storage_mount: "/storage"
backups_dir: "{{ storage_mount }}/backups"

# Media
media_apps_dir: "/srv/media"
media_appdata_backup_dir: "{{ backups_dir }}/appdata"
downloads_dir: "{{ data_mount }}/downloads"
movies_dir: "{{ storage_mount }}/movies"
series_dir: "{{ storage_mount }}/series"

# Minecraft
minecraft_apps_dir: "/srv/minecraft"
minecraft_world_backup_dir: "{{ backups_dir }}/minecraft"

minecraft_version: "1.16.4"
minecraft_heap_mb: 9216

# Public
public_apps_dir: "/srv/public"
