- name: Install docker packages
  pacman:
    name: "docker docker-compose"
    state: "present"

- name: Enable Docker
  systemd:
    name: "docker.service"
    state: "started"
    enabled: yes

- name: Create docker directories
  loop:
    - { path: "{{ docker_apps_dir }}" }
    - { path: "{{ docker_appdata_dir }}" }
  file:
    path: "{{ item.path }}"
    state: "directory"
    owner: "root"
    group: "docker"
    mode: 0750

- name: Copy appdata files
  loop:
    - { src: "appdata", dest: "{{ docker_appdata_dir }}" }
    - { src: "www", dest: "/srv" }
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "docker-appdata"
    group: "docker-appdata"
    directory_mode: 0750
    mode: 0640

- name: Copy appdata templates
  with_filetree: "appdata/"
  when: "item.state == 'file'"
  template:
    src: "{{ item.src }}"
    dest: "{{ docker_appdata_dir }}/{{ item.path }}"
    owner: "docker-appdata"
    group: "docker-appdata"
    mode: 0640

- name: Copy docker compose
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ docker_apps_dir }}/docker-compose.yml"
    owner: "root"
    group: "docker"
    mode: 0640
    validate: "docker-compose -f %s config"
