- name: Install docker packages
  pacman:
    name: "docker docker-compose"
    state: "present"

- file:
    state: "directory"
    path: "/etc/systemd/system/docker.service.d"
    owner: "root"
    group: "root"
    mode: 0755
- name: Copy docker service unit overrides
  notify:
    - reload systemd
    - restart docker
  copy:
    dest: "/etc/systemd/system/docker.service.d/10-args.conf"
    owner: "root"
    group: "root"
    mode: 0644
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd -H fd:// --iptables=false --bip={{ docker_net_host }} --fixed-cidr={{ docker_net_host }}

- name: Enable Docker
  systemd:
    name: "docker.service"
    state: "started"
    enabled: yes

- name: Create docker directories
  file:
    path: "{{ docker_apps_dir }}"
    state: "directory"
    owner: "root"
    group: "docker"
    mode: 0750

# TODO: Copying whole directories is tricky. Because it resets some permissions then re-hardens them. So we get tons of "changed" output

- name: Copy appdata files
  copy:
    src: "appdata"
    dest: "{{ docker_appdata_dir }}/.."
    owner: "docker-appdata"
    group: "docker-appdata"
    directory_mode: 0750
    mode: 0640
- name: Copy www files
  copy:
    src: "www"
    dest: "/srv"
    owner: "docker-appdata"
    group: "docker-appdata"
    directory_mode: 0755
    mode: 0644

- name: Copy appdata templates
  with_filetree: "../templates/appdata/"
  when: "item.state == 'file'"
  template:
    src: "{{ item.src }}"
    dest: "{{ docker_appdata_dir }}/{{ item.path | replace('.j2', '') }}"
    owner: "docker-appdata"
    group: "docker-appdata"
    mode: "u=rwX,g=rX,o="

- name: Harden appdata permissions
  loop:
    - { state: "directory", path: "{{ docker_appdata_dir }}/traefik/acme" }
    - { state: "file", path: "{{ docker_appdata_dir }}/traefik/traefik.d/monitoring.htpasswd" }
    - { state: "file", path: "{{ docker_appdata_dir }}/traefik/traefik.d/gce_service_account.json" }
    - { state: "directory", path: "{{ docker_appdata_dir }}/mosquitto/data" }
    - { state: "file", path: "{{ docker_appdata_dir }}/mosquitto/config/passwords" }
    - { state: "file", path: "{{ docker_appdata_dir }}/mosquitto/config/acl" }
    - { state: "file", path: "{{ docker_appdata_dir }}/appdata-backup/gcs_auth.json" }
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    recurse: "{{ (item.state == 'directory') | bool }}"
    mode: "u=rwX,go="

- name: Copy docker compose
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ docker_apps_dir }}/docker-compose.yml"
    owner: "root"
    group: "docker"
    mode: 0640
    validate: "docker-compose -f %s config"
