- name: Copy NFTables configuration
  notify: reload nftables
  template:
    src: "etc/nftables.conf.j2"
    dest: "/etc/nftables.conf"
    force: yes
    owner: "root"
    group: "root"
    mode: 0600
    validate: "nft -c -f %s"

- name: Enable NFTables
  systemd:
    name: "nftables.service"
    state: "started"
    enabled: yes

- name: Update hosts file
  blockinfile:
    state: "present"
    path: "/etc/hosts"
    block: |
      {{ living_room_tv_ip }} tv-lr.devices.local
