- name: Create system groups
  group:
    name: '{{ item.name }}'
    gid: '{{ item.gid }}'
    state: present
  loop:
    - { name: &appdata 'docker-appdata', gid: '{{ system_appdata_gid }}' }

- name: Create appdata user
  user:
    name: *appdata
    group: *appdata
    uid: '{{ system_appdata_uid }}'
    create_home: no
    shell: '/usr/bin/nologin'
    state: present
