- name: "Copy UDEV rules"
  loop:
    - { name: "99-husbzb.rules" }
    - { name: "99-ups.rules" }
  notify: "reload udev"
  ansible.builtin.template:
    src: "udev/{{ item.name }}.j2"
    dest: "/etc/udev/rules.d/{{ item.name }}"
    owner: "root"
    group: "root"
    mode: 0644
