- name: "Create Elastic's directories"
  loop:
    - { path: "{{ docker_apps_dir }}/monitoring", mode: "u=rwx,go=rx" }
    - { path: "{{ docker_appdata_dir }}/elasticsearch", mode: "u=rwx,g=rx,o=" }
    - { path: "{{ docker_appdata_dir }}/filebeat", mode: "u=rwx,g=rx,o=" }
    - { path: "{{ docker_appdata_dir }}/journalbeat", mode: "u=rwx,g=rx,o=" }
    - { path: "{{ docker_appdata_dir }}/kibana", mode: "u=rwx,g=rx,o=" }
    - { path: "{{ docker_appdata_dir }}/metricbeat", mode: "u=rwx,g=rx,o=" }
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "directory"
    owner: "root"
    group: "docker"
    mode: "{{ item.mode }}"

- name: "Copy Elastic's files"
  loop:
    - { path: "elasticsearch/elasticsearch.yml", mode: "u=rw,g=r,o=" }
    - { path: "elasticsearch/elasticsearch.keystore", mode: "u=rw,g=r,o=", host_file: true }
  ansible.builtin.copy:
    src: "{{ item.host_file | default(False) | ternary(host_files, '') }}appdata/{{ item.path }}"
    dest: "{{ docker_appdata_dir }}/{{ item.path }}"
    owner: "root"
    group: "root"
    mode: "{{ item.mode }}"

- name: "Copy Elastic templates"
  loop:
    - { path: "elasticsearch/roles.yml", mode: "u=rw,g=r,o=" }
    - { path: "filebeat/filebeat.yml", mode: "u=rw,g=r,o=" }
    - { path: "journalbeat/journalbeat.yml", mode: "u=rw,g=r,o=" }
    - { path: "kibana/kibana.yml", mode: "u=rw,g=r,o=" }
    - { path: "metricbeat/metricbeat.yml", mode: "u=rw,g=r,o=" }
  ansible.builtin.template:
    src: "{{ item.host_file | default(False) | ternary(host_files, '') }}appdata/{{ item.path }}.j2"
    dest: "{{ docker_appdata_dir }}/{{ item.path }}"
    owner: "root"
    group: "root"
    mode: "{{ item.mode }}"

- name: "Copy docker compose"
  ansible.builtin.template:
    src: "docker/monitoring/docker-compose.yml.j2"
    dest: "{{ docker_apps_dir }}/monitoring/docker-compose.yml"
    owner: "root"
    group: "docker"
    mode: 0640
    validate: "docker-compose -f %s config"
