- name: "Check if backup restoration is required"
  register: "acl_backup"
  ansible.builtin.stat:
    path: "{{ automate_appdata_dir }}/acl.txt"

- name: "Restore backup"
  when: "not acl_backup.stat.exists"
  block:
    - name: "Copy initial backed up appdata"
      community.docker.docker_container:
        auto_remove: true
        cleanup: true
        detach: false
        keep_volumes: false
        image: "bcardiff/rclone:latest"
        name: "rclone_restore_backup"
        state: "started"
        env:
          TZ: "{{ timezone }}"
          SYNC_SRC: "{{ gce_backup_key }}:{{ gce_backup_bucket }}"
          SYNC_DEST: "/content"
          SYNC_OPTS: "-v -x"
        volumes:
          - "{{ automate_appdata_dir }}:/content"
          - "{{ automate_appdata_dir }}/appdata-backup:/config"

    - name: "Restore backed up ACLs"
      command: "getfacl --restore=acl.txt"
      args:
        chdir: "{{ automate_appdata_dir }}"
