- name: "Start automate apps"
  community.docker.docker_compose:
    project_src: "{{ automate_apps_dir }}"
    state: "present"
    build: true
    pull: true
- name: "Start public apps"
  community.docker.docker_compose:
    project_src: "{{ automate_apps_dir }}"
    state: "present"
    build: true
    pull: true
