- name: "Create directories"
  loop:
    - { path: "" }
  ansible.builtin.file:
    path: "{{ error_pages.config_dir }}/{{ item.path }}"
    state: "directory"
    owner: "root"
    group: "docker"
    mode: 0750

- name: "Copy www files"
  ansible.builtin.copy:
    src: "public/error-pages/www"
    dest: "{{ error_pages.config_dir }}"
    owner: "root"
    group: "root"
    directory_mode: 0755
    mode: 0644

- name: "Create service"
  include_role:
    name: "container"
    tasks_from: "service-fragment"
  vars:
    default_fragment:
      name: "error-pages"
      definition:
        image: "nginxinc/nginx-unprivileged:alpine"
        restart: "unless-stopped"
        environment:
          TZ: "{{ timezone }}"
        volumes:
          - "{{ error_pages.config_dir }}/www:/usr/share/nginx/html:ro"
    fragment: |
      {% if error_pages.fragment.proxy is mapping -%}
        {% set name = error_pages.fragment.name | default(default_fragment.name, True) -%}
        {%
          set default_proxy = {
            "proxy": {
              "port": 8080,
            },
            "definition": {
              "labels": {
                "traefik.http.routers." ~ name ~ ".rule": "HostRegexp(`{catchall:.+}`)",
                "traefik.http.routers." ~ name ~ ".priority": 1,
              },
            },
          }
        -%}
      {% endif -%}

      {{
        default_fragment
          | combine(default_proxy | default({}), recursive=True, list_merge='append_rp')
          | combine(error_pages.fragment | default({}), recursive=True, list_merge='append_rp')
          | to_json
      }}
