- name: Set hostname
  ansible.builtin.template:
    src: "etc/hostname.j2"
    dest: "/etc/hostname"
    owner: "root"
    group: "root"
    mode: 0644

- name: Update hosts file
  ansible.builtin.template:
    src: "etc/hosts.j2"
    dest: '/etc/hosts'
    owner: root
    group: root
    mode: 0644

- name: Configure DNS
  ansible.builtin.file:
    state: "link"
    src: "/run/systemd/resolve/resolv.conf"
    path: "/etc/resolv.conf"
    owner: "root"
    group: "root"

- name: Disable IPV6
  notify: reload kernel
  ansible.builtin.copy:
    dest: "/etc/sysctl.d/40-ipv6.conf"
    owner: "root"
    group: "root"
    mode: 0644
    content: "net.ipv6.conf.all.disable_ipv6=1"

- name: Cleanup old files
  loop:
    - { path: "/etc/modprobe.d/noiptables.conf" }
    - { path: "/usr/local/sbin/iptables" }
  ansible.builtin.file:
    state: "absent"
    path: "{{ item.path }}"
