- name: Update pacman cache
  changed_when: false
  pacman:
    update_cache: yes

- name: Install common libraries
  pacman:
    name: git nftables iptables-nft openssh python sudo tmux vim
    state: present

- name: Install Yay (AUR wrapper)
  become: no
  aur:
    name: yay
    use: makepkg
    skip_installed: yes

- name: Configure journald limits
  block:
    - name: Create journald conf directory
      file:
        state: "directory"
        path: "/etc/systemd/journald.conf.d"
        owner: "root"
        group: "root"
        mode: 0755
    - name: Copy journald configs
      notify: reload journald
      copy:
        dest: "/etc/systemd/journald.conf.d/10-max_size.conf"
        owner: "root"
        group: "root"
        mode: 0644
        content: |
          [Journal]
          SystemMaxUse=2G

- name: Increase memory maps
  notify: reload kernel
  copy:
    dest: "/etc/sysctl.d/50-memory.conf"
    owner: "root"
    group: "root"
    mode: 0644
    content: "vm.max_map_count=262144"
