- name: Install Fish
  community.general.pacman:
    name:
      - fish
    state: present

- name: Create groups
  loop:
    - ssh
    - poweroff
  ansible.builtin.group:
    name: '{{ item }}'
    state: present

- name: Create sudoer rule for wheel
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/20-wheel
    line: '%wheel ALL=(ALL) ALL'
    create: yes
    owner: root
    group: root
    mode: 0440
    validate: 'visudo -cf %s'

- name: Create sudoer rule for poweroff
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/30-poweroff
    line: '%poweroff ALL=NOPASSWD: /usr/bin/poweroff, /usr/bin/halt, /usr/bin/reboot'
    create: yes
    owner: root
    group: root
    mode: 0440
    validate: 'visudo -cf %s'

- name: Create and configure `ansible`
  block:
    - name: Create user
      ansible.builtin.user:
        name: ansible
        groups: ssh
        append: no
        state: present

    - name: Create .ssh/ directory
      ansible.builtin.file:
        path: "/home/ansible/.ssh"
        state: "directory"
        owner: "ansible"
        group: "ansible"
        mode: 0740

- name: Create and configure `avatar`
  block:
    - name: Create user
      ansible.builtin.user:
        name: "{{ users.avatar.username }}"
        groups: wheel,ssh,poweroff
        append: yes
        create_home: yes
        state: present
        shell: /usr/bin/fish
        password: "{{ users.avatar.password }}"

    - name: Create .ssh/ directory
      ansible.builtin.file:
        path: "/home/avatar/.ssh"
        state: "directory"
        owner: "{{ users.avatar.username }}"
        group: "{{ users.avatar.username }}"
        mode: 0740

    - name: Add authorized keys
      ansible.posix.authorized_key:
        exclusive: yes
        key: '{{ users.avatar.pub_key }}'
        user: "{{ users.avatar.username }}"
        state: present

- name: Create and configure `homeassistant`
  block:
    - name: Create user
      ansible.builtin.user:
        name: "{{ users.homeassistant.username }}"
        groups: ssh,poweroff
        create_home: yes
        state: present
        password: '{{ users.homeassistant.password }}'

    - name: Create .ssh/ directory
      ansible.builtin.file:
        path: "/home/homeassistant/.ssh"
        state: "directory"
        owner: "{{ users.homeassistant.username }}"
        group: "{{ users.homeassistant.username }}"
        mode: 0740

    - name: Add authorized keys
      ansible.posix.authorized_key:
        exclusive: yes
        key: "{{ users.homeassistant.pub_key }}"
        user: "{{ users.homeassistant.username }}"
        state: present
