- name: "Create user"
  register: "deluge_user"
  ansible.builtin.user:
    append: false
    create_home: false
    group: "{{ deluge.group | default(omit) }}"
    groups: "{{ deluge.extra_groups | default([]) | map(attribute = 'name') | join(',') }}"
    name: "deluge"
    shell: "/usr/bin/nologin"
    state: "present"
    system: true

- name: "Create config directories"
  loop:
    - { path: "" }
    - { path: "custom-cont-init.d" }
  ansible.builtin.file:
    <<: &owner_group
      owner: "{{ deluge_user.name }}"
      group: "{{ deluge.group | default(deluge_user.name) }}"
    path: "{{ deluge.config_dir }}/{{ item.path }}"
    state: "directory"
    mode: 0750

- name: "Create data directories"
  loop:
    - { path: "" }
    - { path: "active" }
    - { path: "completed" }
  ansible.builtin.file:
    <<: *owner_group
    path: "{{ deluge.downloads_dir }}/{{ item.path }}"
    state: "directory"
    mode: 0750

- name: "Add supplementary group support"
  ansible.builtin.copy:
    <<: *owner_group
    src: "extra_groups.sh"
    dest: "{{ deluge.config_dir }}/custom-cont-init.d/extra_groups.sh"
    mode: 0640

- name: "Create service fragment"
  include_role:
    name: "container"
    tasks_from: "service-fragment"
  vars:
    default_fragment:
      name: "deluge"
      definition:
        image: "ghcr.io/linuxserver/deluge:latest"
        environment:
          TZ: "{{ timezone }}"
          PUID: "{{ deluge_user.uid }}"
          PGID: "{{ deluge_user.group }}"
          EXTRA_GID: "{{ deluge.extra_groups | default([]) | map(attribute = 'gid') | join(' ') }}"
          UMASK_SET: "027"
        labels:
          traefik.http.services.deluge.loadbalancer.server.port: 8112
        restart: "unless-stopped"
        volumes:
          - "{{ deluge.config_dir }}:/config"
          - "{{ deluge.blackhole_dir }}:/blackhole:ro"
          - "{{ deluge.downloads_dir }}:/downloads"
    fragment: |
      {{
        default_fragment
          | combine(deluge.fragment | default({}), recursive=True, list_merge='append_rp')
          | to_json
      }}
