- name: "Create directories"
  loop:
    - { path: "" }
  ansible.builtin.file:
    path: "{{ config_dir }}/{{ item.path }}"
    state: "directory"
    owner: "root"
    group: "docker"
    mode: 0750

- name: "Copy configurations"
  loop:
    - { filename: "traefik.toml" }
  ansible.builtin.template:
    src: "{{ item.filename }}.j2"
    dest: "{{ config_dir }}/{{ item.filename }}"
    owner: "root"
    group: "docker"
    mode: 0640

- name: "Create service fragment"
  include_role:
    name: "app"
    tasks_from: "service-fragment"
  vars:
    fragment:
      name: "proxy"
      definition: |
        {{
          {
            "image": "traefik:2.3",
            "environment": {
              "TZ": timezone
            },
            "labels": {
              "traefik.http.routers.traefik.service": "api@internal"
            },
            "ports": [ "80:80" ],
            "restart": "unless-stopped",
            "volumes": [
              "/var/run/docker.sock:/var/run/docker.sock:ro",
              config_dir ~ "/traefik.toml:/traefik.toml:ro"
            ]
          } | combine(fragment_definition | default({}), recursive=True, list_merge='append_rp')
            | to_json
        }}
