# Inventory: PRODUCTION
# Server: Avatar-Automate

ansible_host: "avatar-automate-ansible"

ssh_port: "{{ network.servers.automate.ports.ssh }}"
internal_ip: "{{ network.servers.automate.ip }}"
internal_hostname: "{{ network.servers.automate.host }}"

wan_if: "enp0s25"

homeassistant_config_owner: "Chris-V"
homeassistant_config_repo: "homeassistant-config"
