- name: "Create user"
  register: "jellyfin_user"
  ansible.builtin.user:
    append: false
    create_home: false
    group: "{{ jellyfin.group | default(omit) }}"
    groups: "{{ jellyfin.extra_groups | default([]) | map(attribute = 'name') | join(',') }}"
    name: "jellyfin"
    shell: "/usr/bin/nologin"
    state: "present"
    system: true

- name: "Create config directories"
  loop:
    - { path: "" }
    - { path: "custom-cont-init.d" }
  ansible.builtin.file:
    <<: &owner_group
      owner: "{{ jellyfin_user.name }}"
      group: "{{ jellyfin.group | default(jellyfin_user.name) }}"
    path: "{{ jellyfin.config_dir }}/{{ item.path }}"
    state: "directory"
    mode: 0750

- name: "Create data directories"
  ansible.builtin.file:
    <<: *owner_group
    path: "{{ jellyfin.transcode_dir }}"
    state: "directory"
    mode: 0750

- name: "Add supplementary group support"
  ansible.builtin.copy:
    <<: *owner_group
    src: "extra_groups.sh"
    dest: "{{ jellyfin.config_dir }}/custom-cont-init.d/extra_groups.sh"
    mode: 0640

- name: "Create service fragment"
  include_role:
    name: "container"
    tasks_from: "service-fragment"
  vars:
    default_fragment:
      name: "jellyfin"
      definition:
        image: "ghcr.io/linuxserver/jellyfin:latest"
        devices: ["/dev/dri:/dev/dri"]
        environment:
          TZ: "{{ timezone }}"
          PUID: "{{ jellyfin_user.uid }}"
          PGID: "{{ jellyfin_user.group }}"
          EXTRA_GID: "{{ jellyfin.extra_groups | default([]) | map(attribute = 'gid') | join(' ') }}"
          UMASK_SET: "027"
        labels:
          traefik.http.services.jellyfin.loadbalancer.server.port: 8096
        restart: "unless-stopped"
        volumes:
          - "{{ jellyfin.config_dir }}:/config"
          - "{{ jellyfin.series_dir }}:/media/series:ro"
          - "{{ jellyfin.movies_dir }}:/media/movies:ro"
          - "{{ jellyfin.transcode_dir }}:/transcode"
    fragment: |
      {{
        default_fragment
          | combine(jellyfin.fragment | default({}), recursive=True, list_merge='append_rp')
          | to_json
      }}
