- name: "Create plant-gateway directories"
  loop:
    - { path: "" }
  ansible.builtin.file:
    path: "{{ docker_appdata_dir }}/plantgw/{{ item.path }}"
    state: "directory"
    owner: "docker-appdata"
    group: "docker-appdata"
    mode: 0750

- name: "Copy plant-gateway files"
  loop:
    - { filename: "DST_Root_CA_X3.pem" }
  ansible.builtin.copy:
    src: "{{ item.host_file | default(False) | ternary(host_files, '') }}appdata/plantgw/{{ item.filename }}.j2"
    dest: "{{ docker_appdata_dir }}/plantgw/{{ item.filename }}"
    owner: "docker-appdata"
    group: "docker-appdata"
    mode: 0640

- name: "Copy plant-gateway templates"
  loop:
    - { host_file: true, filename: "plantgw.yaml" }
  ansible.builtin.template:
    src: "{{ item.host_file | default(False) | ternary(host_files, '') }}appdata/plantgw/{{ item.filename }}.j2"
    dest: "{{ docker_appdata_dir }}/plantgw/{{ item.filename }}"
    owner: "docker-appdata"
    group: "docker-appdata"
    mode: 0640
