- name: "Create config directories"
  loop:
    - { path: "" }
  ansible.builtin.file:
    owner: "root"
    group: "root"
    path: "{{ zwavejs2mqtt.config_dir }}/{{ item.path }}"
    state: "directory"
    mode: 0750

- name: "Create service fragment"
  include_role:
    name: "container"
    tasks_from: "service-fragment"
  vars:
    default_fragment:
      name: "zwavejs2mqtt"
      definition:
        image: "ghcr.io/zwave-js/zwavejs2mqtt:{{ zwavejs2mqtt_version }}"
        restart: "unless-stopped"
        devices:
          - "{{ zwavejs2mqtt.usb_path }}:/dev/zwave"
        environment:
          NETWORK_KEY: "{{ zwavejs2mqtt.network_key }}"
          SESSION_SECRET: "{{ zwavejs2mqtt.session_secret_salt }}"
        volumes:
          - "{{ zwavejs2mqtt.config_dir }}:/usr/src/app/store"
    fragment: |
      {% if zwavejs2mqtt.fragment.proxy is mapping -%}
        {% set name = zwavejs2mqtt.fragment.name | default(default_fragment.name, True) -%}
        {%
          set default_proxy = {
            "proxy": {
              "port": 8091,
            },
            "definition": {
              "labels": {
                "traefik.http.routers." ~ name ~ "_ws.entryPoints": zwavejs2mqtt.fragment.proxy.entrypoint,
                "traefik.http.routers." ~ name ~ "_ws.rule": "Host(`" ~ zwavejs2mqtt.fragment.proxy.subdomain ~ "." ~ domain_name ~ "`) && Header(`Upgrade`, `websocket`)",
                "traefik.http.routers." ~ name ~ "_ws.service": name ~ "_ws",
                "traefik.http.services." ~ name ~ "_ws.loadbalancer.server.port": 3000,
              },
            },
          }
        -%}
      {% endif -%}

      {{
        default_fragment
          | combine(default_proxy | default({}), recursive=True, list_merge='append_rp')
          | combine(zwavejs2mqtt.fragment | default({}), recursive=True, list_merge='append_rp')
          | to_json
      }}
