- name: Install bluez
  community.general.pacman:
    name: "bluez"
    state: "present"

- name: Install bluetooth utils (AUR)
  become: no
  aur:
    name:
      - pi-bluetooth
      - bluez-utils-compat
    aur_only: yes

- name: Enable bluetooth on boot
  register: "bluetooth_autoenable"
  ansible.builtin.lineinfile:
    path: "/etc/bluetooth/main.conf"
    regexp: "^AutoEnable="
    insertafter: '^#AutoEnable='
    line: "AutoEnable=true"
    state: "present"

- name: Enable bluetoothd experimental flag
  block:
    - name: Create systemd bluetooth config directory
      ansible.builtin.file:
        state: "directory"
        path: "/etc/systemd/system/bluetooth.service.d"
        owner: "root"
        group: "root"
        mode: 0755
    - name: Copy bluetooth service unit overrides
      register: "bluetooth_experimental"
      ansible.builtin.copy:
        src: "etc/systemd/system/bluetooth.service.d/override.conf"
        dest: "/etc/systemd/system/bluetooth.service.d/override.conf"
        owner: "root"
        group: "root"
        mode: "0644"

- name: Enable bluetooth
  register: "bluetooth_service"
  ansible.builtin.systemd:
    name: "bluetooth.service"
    daemon_reload: yes
    state: "started"
    enabled: yes
- name: Restart bluetooth
  when: "(bluetooth_autoenable.changed or bluetooth_service.changed) and not bluetooth_service.changed"
  ansible.builtin.systemd:
    name: "bluetooth.service"
    daemon_reload: yes
    state: "restarted"
