- name: Install docker packages
  pacman:
    name: docker docker-compose
    state: present

- name: Enable Docker
  systemd:
    name: docker.service
    state: started
    enabled: yes

- name: Create docker directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "root"
    group: "docker"
    mode: 0770
  loop:
    - { path: '{{ docker_apps_dir }}' }

- name: Copy docker images
  copy:
    src: 'docker-images'
    dest: '{{ docker_apps_dir }}'
    owner: "root"
    group: "docker"
    directory_mode: "ug=rwx,o="
    mode: "preserve"

- name: Copy app data
  copy:
    src: 'appdata'
    dest: '{{ docker_apps_dir }}'
    owner: "root"
    group: "docker"
    directory_mode: "ug=rwx,o="
    mode: "preserve"

- name: Copy plant gateway config
  template:
    src: 'host_files/{{ inventory_hostname }}/plantgw.yaml.j2'
    dest: '{{ docker_appdata_dir }}/plantgw/plantgw.yaml'
    owner: "root"
    group: "docker"
    mode: 0660

- name: Copy docker compose
  template:
    src: "docker-compose.yml.j2"
    dest: '{{ docker_apps_dir }}/docker-compose.yml'
    owner: "root"
    group: "docker"
    mode: 0660
    validate: 'docker-compose -f %s config'
