- name: "Configure docker-apps structure"
  block:
    - name: "Create docker apps root"
      ansible.builtin.file:
        path: "{{ docker_apps_dir }}"
        state: "directory"
        owner: "root"
        group: "docker"
        mode: 0770
    - name: "Create docker appdata root"
      ansible.builtin.file:
        path: "{{ docker_appdata_dir }}"
        state: "directory"
        owner: "root"
        group: "docker"
        mode: 0770

- name: "Configure Traefik"
  import_tasks: "docker-apps/traefik.yml"

- name: "Configure Plant-Gateway"
  import_tasks: "docker-apps/plant-gateway.yml"

- name: "Copy docker compose"
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ docker_apps_dir }}/docker-compose.yml"
    owner: "root"
    group: "docker"
    mode: 0660
    validate: "docker-compose -f %s config"

- name: "Cleanup old files"
  loop:
    - { path: "{{ docker_apps_dir }}/docker-images" }
  ansible.builtin.file:
    state: "absent"
    path: "{{ item.path }}"
