- name: "Create docker-apps structure"
  loop:
    - { path: "{{ docker_apps_dir }}" }
    - { path: "{{ docker_apps_dir }}/fragments" }
    - { path: "{{ docker_appdata_dir }}" }
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "directory"
    owner: "root"
    group: "docker"
    mode: 0770

- name: "Create Public network fragment"
  include_role:
    name: "app"
    tasks_from: "network-fragment"
  vars:
    dest: "{{ docker_apps_dir }}/fragments/public.network.yml"
    fragment:
      name: "public"
      definition:
        driver: "bridge"
        ipam:
          driver: "default"
          config:
            - subnet: "{{ docker_net_public }}"

- name: "Glances"
  include_role:
    name: "app.glances"
  vars:
    dest: "{{ docker_apps_dir }}/fragments/glances.service.yml"
    glances:
      fragment:
        definition:
          labels:
            avatar.subdomain: "glances"
          networks:
            public: {}

- name: "Plant-Gateway"
  include_role:
    name: "app.plantgateway"
  vars:
    dest: "{{ docker_apps_dir }}/fragments/plant-gateway.service.yml"

- name: "Traefik"
  include_role:
    name: "app.traefik"
  vars:
    dest: "{{ docker_apps_dir }}/fragments/traefik.service.yml"
    traefik:
      config_dir: "{{ docker_appdata_dir }}/traefik"
      domain: "{{ internal_hostname }}"
      trusted_ips: "{{ network.servers.automate.ip }}/32"
      fragment:
        definition:
          labels:
            avatar.subdomain: "traefik"
          networks:
            public:
              ipv4_address: "{{ docker_ip_proxy }}"

- name: "Create docker-compose.yml"
  include_role:
    name: "app"
    tasks_from: "merge-fragments"
  vars:
    src: "{{ docker_apps_dir }}/fragments/"
    dest: "{{ docker_apps_dir }}/docker-compose.yml"
