- name: Install docker packages
  community.general.pacman:
    name: "docker docker-compose"
    state: "present"

- name: Configure docker service
  block:
    - name: Create systemd docker config directory
      ansible.builtin.file:
        state: "directory"
        path: "/etc/systemd/system/docker.service.d"
        owner: "root"
        group: "root"
        mode: 0755
    - name: Copy docker service unit overrides
      notify:
        - reload systemd
        - restart docker
      ansible.builtin.template:
        src: "etc/systemd/system/docker.service.d/10-args.conf.j2"
        dest: "/etc/systemd/system/docker.service.d/10-args.conf"
        owner: "root"
        group: "docker"
        mode: 0644

- name: Enable Docker
  ansible.builtin.systemd:
    name: "docker.service"
    state: "started"
    enabled: yes

- name: Create docker directories
  loop:
    - { path: '{{ docker_apps_dir }}' }
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "directory"
    owner: "root"
    group: "docker"
    mode: 0770

- name: Copy docker images
  ansible.builtin.copy:
    src: 'docker-images'
    dest: '{{ docker_apps_dir }}'
    owner: "root"
    group: "docker"
    directory_mode: "ug=rwx,o="
    mode: "preserve"

- name: Copy docker compose
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: '{{ docker_apps_dir }}/docker-compose.yml'
    owner: "root"
    group: "docker"
    mode: 0660
    validate: 'docker-compose -f %s config'

- name: Copy app data
  ansible.builtin.copy:
    src: 'appdata/'
    dest: '{{ docker_appdata_dir }}'
    owner: "root"
    group: "docker"
    directory_mode: 0750
    mode: 0640
- name: Copy app data templates
  loop:
    - { filename: "traefik.toml" }
  ansible.builtin.template:
    src: 'appdata/{{ item.filename }}.j2'
    dest: '{{ docker_appdata_dir }}/{{ item.filename }}'
    owner: 'root'
    group: 'docker'
    mode: 0640

- name: Copy host-specific plant gateway config
  ansible.builtin.template:
    src: "{{ host_files }}plantgw.yaml.j2"
    dest: "{{ docker_appdata_dir }}/plantgw/plantgw.yaml"
    owner: "root"
    group: "docker"
    mode: 0640
