- name: "Disable wireless power saving mode"
  notify: "reload udev"
  ansible.builtin.copy:
    dest: "/etc/udev/rules.d/81-wifi-powersave.rules"
    owner: "root"
    group: "root"
    mode: 0644
    content: |
      ACTION=="add", SUBSYSTEM=="net", KERNEL=="wl*", RUN+="/usr/bin/iw dev $name set power_save off"

- name: "Cleanup old files"
  loop:
    - { path: "/etc/systemd/network/wired.network" }
    - { path: "/etc/systemd/network/wireless.network" }
  ansible.builtin.file:
    state: "absent"
    path: "{{ item.path }}"
