- name: "Create directories"
  loop:
    - { path: "{{ jellyfin.config_dir }}" }
    - { path: "{{ jellyfin.transcode_dir }}" }
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "directory"
    owner: "docker-appdata"
    group: "docker-appdata"
    mode: 0750

- name: "Add supplementary group support"
  ansible.builtin.copy:
    src: "extra_groups.sh"
    dest: "{{ jellyfin.config_dir }}/custom-cont-init.d/extra_groups.sh"
    owner: "root"
    group: "docker"
    directory_mode: 0750
    mode: 0640

- name: "Create service fragment"
  include_role:
    name: "app"
    tasks_from: "service-fragment"
  vars:
    default_fragment:
      name: "jellyfin"
      definition:
        image: "ghcr.io/linuxserver/jellyfin:latest"
        devices: ["/dev/dri:/dev/dri"]
        environment:
          TZ: "{{ timezone }}"
          PUID: "{{ jellyfin.uid }}"
          PGID: "{{ jellyfin.gid }}"
          UMASK_SET: "027"
        labels:
          traefik.http.services.jellyfin.loadbalancer.server.port: 8096
        restart: "unless-stopped"
        volumes:
          - "{{ jellyfin.config_dir }}:/config"
          - "{{ jellyfin.series_dir }}:/media/series:ro"
          - "{{ jellyfin.movies_dir }}:/media/movies:ro"
          - "{{ jellyfin.transcode_dir }}:/transcode"
    fragment: |
      {{
        default_fragment
          | combine(jellyfin.fragment | default({}), recursive=True, list_merge='append_rp')
          | to_json
      }}
