- name: "Activate WOL"
  listen: "activate wol"
  command: "ethtool -s {{ ansible_facts['default_ipv4']['interface'] }} wol g"

- name: "Reload Journald"
  listen: "reload journald"
  ansible.builtin.systemd:
    name: "systemd-journald.service"
    state: "restarted"

- name: "Reload SSHd"
  listen: "reload sshd"
  ansible.builtin.systemd:
    name: "sshd.service"
    state: "reloaded"

- name: "Reload kernel attributes"
  listen: "reload kernel"
  command: "sysctl --system"
- name: "Reload kernel modules"
  listen: "reload kernel"
  ansible.builtin.systemd:
    name: "systemd-modules-load.service"
    state: "restarted"

- name: "Reload udev rules"
  listen: "reload udev"
  command: "udevadm control --reload-rules"
- name: "Trigger udev rules"
  listen: "reload udev"
  command: "udevadm trigger"
