- name: "Create service fragment"
  include_role:
    name: "app"
    tasks_from: "service-fragment"
  vars:
    default_fragment:
      name: "glances"
      definition:
        image: "nicolargo/glances:dev"
        environment:
          TZ: "{{ timezone }}"
          GLANCES_OPT: "-w --enable-plugin sensors"
        labels:
          traefik.http.services.glances.loadbalancer.server.port: 61208
        pid: "host"
        restart: "unless-stopped"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
    fragment: |
      {{
        default_fragment
          | combine(glances.fragment | default({}), recursive=True, list_merge='append_rp')
          | to_json
      }}
