- name: "Create directories"
  loop:
    - { path: "" }
    - { path: "traefik.d" }
  ansible.builtin.file:
    path: "{{ traefik.config_dir }}/{{ item.path }}"
    state: "directory"
    owner: "root"
    group: "docker"
    mode: 0750

- name: "Copy configurations"
  loop:
    - { filename: "traefik.toml" }
  ansible.builtin.template:
    src: "{{ item.filename }}.j2"
    dest: "{{ traefik.config_dir }}/{{ item.filename }}"
    owner: "root"
    group: "docker"
    mode: 0640

- name: "Create service fragment"
  include_role:
    name: "container"
    tasks_from: "service-fragment"
  vars:
    default_fragment:
      name: "traefik"
      definition:
        image: "traefik:2.4"
        environment:
          TZ: "{{ timezone }}"
        labels:
          traefik.http.routers.traefik.service: "api@internal"
        ports: ["80:80"]
        restart: "unless-stopped"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
          - "{{ traefik.config_dir }}/traefik.toml:/traefik.toml:ro"
          - "{{ traefik.config_dir }}/traefik.d:/traefik.d:ro"
    fragment: |
      {{
        default_fragment
          | combine(traefik.fragment | default({}), recursive=True, list_merge='append_rp')
          | to_json
      }}
