- hosts: avatar
  become: yes
  become_user: root
  tasks:
    - import_role:
        name: common

- hosts: media
  become: yes
  become_user: root
  tasks:
    - import_role:
        name: media

- hosts: automate
  become: yes
  become_user: root
  tasks:
    - import_role:
        name: automate

- hosts: relays
  become: yes
  become_user: root
  tasks:
    - import_role:
        name: relay
