- hosts: "avatar"
  become: true
  become_user: "root"
  tasks:
    - tags: ["common"]
      import_role:
        name: "server.common"

- hosts: "automate"
  become: true
  become_user: "root"
  tasks:
    - import_role:
        name: "server.automate"

- hosts: "media"
  become: true
  become_user: "root"
  tasks:
    - import_role:
        name: "server.media"

- hosts: "relays"
  become: true
  become_user: "root"
  tasks:
    - import_role:
        name: "server.relay"
