- hosts: "avatar"
  become: true
  become_user: "root"
  tasks:
    - import_role:
        name: "common"
      tags: [ "common" ]

- hosts: "automate"
  become: true
  become_user: "root"
  tasks:
    - import_role:
        name: "automate"

- hosts: "media"
  become: true
  become_user: "root"
  tasks:
    - import_role:
        name: "media"

- hosts: "relays"
  become: true
  become_user: "root"
  tasks:
    - import_role:
        name: "relay"
