version: "3.7"

x-linuxserver-env: &linuxserver-env
  TZ: America/Toronto
  PUID: 1000
  PGID: 1000

x-localtime-volume: &localtime-volume /etc/localtime:/etc/localtime:ro

networks:
  media:

services:
  vpn:
    container_name: vpn
    image: microbug/cryptostorm-client:latest
    init: true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      CRYPTOSTORM_USERNAME: ${CRYPTOSTORM_USERNAME}
      CRYPTOSTORM_CONFIG_FILE: CA-Montreal_UDP.ovpn
      FORWARDING_PORT: ${DELUGE_INCOMING_PORT}
    volumes:
      - *localtime-volume

  plex:
    container_name: plex
    image: linuxserver/plex:latest
    init: true
    restart: unless-stopped
    networks:
      - media
    environment:
      <<: *linuxserver-env
      VERSION: docker
    ports:
      - ${PLEX_WEB_PORT}:32400
      - ${PLEX_WEB_PORT}:32400/udp
      - 32469:32469 # DLNA Server
      - 32469:32469/udp # DLNA Server
      - 5353:5353/udp # Bonjour/Avahi network discovery
      - 1900:1900/udp # DLNA Server
    volumes:
      - *localtime-volume
      - ${CONFIGS_DIR}/plex:/config
      - ${SERIES_DIR}:/data/tvshows
      - ${MOVIES_DIR}:/data/movies
      - ${PLEX_TRANSCODE_DIR}:/transcode

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    init: true
    restart: unless-stopped
    networks:
      - media
    environment:
      <<: *linuxserver-env
    ports:
      - ${JACKETT_WEB_PORT}:9117
    volumes:
      - *localtime-volume
      - ${CONFIGS_DIR}/jackett:/config
      - ${DOWNLOADS_DIR}/jackett:/downloads

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    init: true
    network_mode: service:vpn
    restart: unless-stopped
    depends_on:
      - vpn
    networks:
      - media
    environment:
      <<: *linuxserver-env
      UMASK_SET: 022
    ports:
      - ${DELUGE_WEB_PORT}:8112
      - ${DELUGE_DAEMON_PORT}:58846
      - ${DELUGE_INCOMING_PORT}:58946
      - ${DELUGE_INCOMING_PORT}:58946/udp
    volumes:
      - *localtime-volume
      - ${CONFIGS_DIR}/deluge:/config
      - ${DOWNLOADS_DIR}/torrents:/downloads

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:preview
    init: true
    restart: unless-stopped
    depends_on:
      - deluge
      - jackett
    networks:
      - media
    environment:
      <<: *linuxserver-env
    ports:
      - ${SONARR_WEB_PORT}:8989
    volumes:
      - *localtime-volume
      - ${CONFIGS_DIR}/sonarr:/config
      - ${SERIES_DIR}:/tv
      - ${DOWNLOADS_DIR}/sonarr:/downloads

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    init: true
    restart: unless-stopped
    depends_on:
      - deluge
      - jackett
    networks:
      - media
    environment:
      <<: *linuxserver-env
    ports:
      - ${RADARR_WEB_PORT}:7878
    volumes:
      - *localtime-volume
      - ${CONFIGS_DIR}/radarr:/config
      - ${MOVIES_DIR}:/movies
      - ${DOWNLOADS_DIR}/radarr:/downloads

  glances:
    container_name: glances
    image: nicolargo/glances:latest-alpine
    init: true
    restart: unless-stopped
    pid: host
    environment:
      GLANCES_OPT: -w
    ports:
      - ${GLANCES_WEB_PORT}:61208
    volumes:
      - *localtime-volume
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIGS_DIR}/glances/glances.conf:/glances/conf/glances.conf
