- name: "Create service fragment: {{ fragment.name }}"
  ansible.builtin.template:
    src: "compose-service.yml.j2"
    dest: "{{ dest }}"
    owner: "root"
    group: "docker"
    mode: 0640
    validate: "{% if validate | default(true) %}docker-compose -f %s config -q{% endif %}"
