- name: "Create service fragment"
  include_role:
    name: "app"
    tasks_from: "service-fragment"
  vars:
    default_fragment:
      name: "vpn"
      definition:
        cap_add: ["NET_ADMIN"]
        image: "microbug/cryptostorm-client:latest"
        environment:
          TZ: "{{ timezone }}"
          CRYPTOSTORM_USERNAME: "{{ vpn.username }}"
          CRYPTOSTORM_CONFIG_FILE: "{{ vpn.config_file | default('Balancer_UDP.ovpn') }}"
          CONNECTION_PORT: 443
        restart: "unless-stopped"
    fragment: |
      {{
        default_fragment
          | combine(
              {"environment": {"FORWARDING_PORT": vpn.forwarding_port}} if vpn.forwarding_port is number else {},
              recursive=True,
            )
          | combine(vpn.fragment | default({}), recursive=True, list_merge='append_rp')
          | to_json
      }}
