- import_tasks: "mounts.yml"
  tags: [ "system" ]

- name: "Media"
  tags: [ "docker", "media" ]
  import_role:
    name: "app.media"

- name: "Minecraft"
  tags: [ "docker", "minecraft" ]
  import_tasks: "minecraft.yml"
