- name: "Install mount packages"
  community.general.pacman:
    name:
      - "arch-install-scripts"
      - "btrfs-progs"
      - "fuse3"
      - "hdparm"
      - "smartmontools"
      - "xfsprogs"
    state: "present"

- name: "Install mount packages (AUR)"
  become: false
  aur:
    name:
      - "mergerfs"
      - "snapraid"
    state: "present"

- name: "Create mount directories"
  loop:
    - { path: "/mnt/storage" }
    - { path: "{{ data_mount }}" }
    - { path: "{{ storage_mount }}" }
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: 0755

- name: "Mount data disk"
  ansible.posix.mount:
    state: "mounted"
    src: "LABEL=data"
    path: "/data"
    fstype: "btrfs"
    opts: "rw,relatime,space_cache=v1,subvolid=5,subvol=/"
    dump: "0"
    passno: "0"

- name: "Mount storage disk 1"
  ansible.posix.mount:
    state: "mounted"
    src: "PARTLABEL=storage1"
    path: "/mnt/storage/disk1"
    fstype: "xfs"
    opts: "defaults"
    dump: "0"
    passno: "0"

- name: "Mount storage merge"
  ansible.posix.mount:
    state: "mounted"
    src: "/mnt/storage/disk*"
    path: "{{ storage_mount }}"
    fstype: "fuse.mergerfs"
    opts: "direct_io,defaults,allow_other,minfreespace=50G,fsname=mergerfs-storage"
    dump: "0"
    passno: "0"

- name: "Create shared directories"
  loop:
    - { path: "{{ backups_dir }}" }
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "directory"
    recurse: false
    owner: "root"
    group: "root"
    mode: 0750
