name: "CI"

"on": ["push"]

jobs:
  check:
    name: "Static check"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Lint"
        run: "make lint"
