- name: Install docker packages
  pacman:
    name: "docker docker-compose"
    state: "present"

- block:
    - file:
        state: "directory"
        path: "/etc/systemd/system/docker.service.d"
        owner: "root"
        group: "root"
        mode: 0755
    - name: Copy docker service unit overrides
      notify:
        - reload systemd
        - restart docker
      template:
        src: "etc/systemd/system/docker.service.d/10-args.conf.j2"
        dest: "/etc/systemd/system/docker.service.d/10-args.conf"
        owner: "root"
        group: "docker"
        mode: 0644

- name: Enable Docker
  systemd:
    name: "docker.service"
    state: "started"
    enabled: yes

- name: Create data directories
  loop:
    - { path: "{{ backups_dir }}" }
    - { path: "{{ appdata_backups_dir }}" }
    - { path: "{{ minecraft_backups_dir }}" }
    - { path: "{{ series_dir }}", group: "media", mode: "ug=rwx,o=rx" }
    - { path: "{{ movies_dir }}", group: "media", mode: "ug=rwx,o=rx" }
    - { path: "{{ downloads_dir }}", group: "data", mode: "ug=rwx,o=rx" }
    - { path: "{{ deluge_completed_dir }}", group: "data", mode: "ug=rwx,o=rx" }
    - { path: "{{ deluge_downloads_dir }}", group: "data", mode: "ug=rwx,o=rx" }
    - { path: "{{ jackett_downloads_dir }}", group: "data", mode: "ug=rwx,o=rx" }
    - { path: "{{ minecraft_data_dir }}" }
    - { path: "{{ minecraft_map_dir }}", group: "data", mode: "ug=rwx,o=rx" }
    - { path: "{{ plex_transcode_dir }}" }
  file:
    path: "{{ item.path }}"
    state: "directory"
    recurse: no
    owner: "docker-appdata"
    group: "{{ item.group | default('docker-appdata', true) }}"
    mode: "{{ item.mode | default('ug=rwx,o=', true) }}"

- name: Create docker directories
  loop:
    - "{{ docker_srv_dir }}"
  file:
    path: "{{ item }}"
    state: "directory"
    owner: "root"
    group: "docker"
    mode: "ug=rwX,o="

- name: Copy docker images
  copy:
    src: "docker-images"
    dest: "{{ docker_srv_dir }}"
    owner: "root"
    group: "docker"
    directory_mode: "ug=rwx,o="
    mode: "ug+rw,o=" # Preserve exec. bit where applicable

- name: Copy docker compose
  loop:
    - "docker-compose"
    - "docker-compose.jobs"
  template:
    src: "{{ item }}.yml.j2"
    dest: "{{ docker_srv_dir }}/{{ item }}.yml"
    owner: "root"
    group: "docker"
    mode: "ug=rw,o="
    validate: "docker-compose -f %s config"

- name: Copy initial app configs
  unarchive:
    creates: "{{ docker_appdata_dir }}"
    src: "{{ appdata_archive }}"
    dest: "{{ docker_srv_dir }}"

- name: Copy managed app configs
  copy:
    src: "appdata/"
    dest: "{{ docker_appdata_dir }}"
    owner: "docker-appdata"
    group: "docker-appdata"
    directory_mode: "u=rwx,g=rx,o="
    mode: "u+rw,g+r-w,o=" # Preserve exec. bit where applicable

- name: Populate managed app configs
  loop:
    - { filename: "traefik.toml" }
  template:
    src: "appdata/{{ item.filename }}.j2"
    dest: "{{ docker_appdata_dir }}/{{ item.filename }}"
    owner: "docker-appdata"
    group: "docker-appdata"
    mode: "u=rw,g=r,o="
