- name: "Create docker directories"
  loop:
    - { path: "{{ docker_apps_dir }}" }
    - { path: "{{ docker_apps_dir }}/fragments" }
    - { path: "{{ docker_appdata_dir }}" }
    - { path: "{{ docker_apps_dir }}/jobs" }
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "directory"
    owner: "root"
    group: "docker"
    mode: 0770

- name: "Create network fragments"
  loop:
    - { name: "public", subnet: "{{ docker_net_public }}" }
    - { name: "glances", subnet: "{{ docker_net_glances }}" }
    - { name: "media", subnet: "{{ docker_net_media }}" }
    - { name: "minecraft", subnet: "{{ docker_net_minecraft }}" }
  include_role:
    name: "app"
    tasks_from: "network-fragment"
  vars:
    dest: "{{ docker_apps_dir }}/fragments/{{ item.name }}.network.yml"
    fragment:
      name: "{{ item.name }}"
      definition:
        driver: "bridge"
        ipam:
          driver: "default"
          config:
            - subnet: "{{ item.subnet }}"

- name: "LEGACY: Create data directories"
  loop:
    - { path: "{{ backups_dir }}" }
    - { path: "{{ appdata_backups_dir }}" }
    - { path: "{{ minecraft_backups_dir }}" }
    - { path: "{{ series_dir }}", group: "media", mode: "ug=rwx,o=rx" }
    - { path: "{{ movies_dir }}", group: "media", mode: "ug=rwx,o=rx" }
    - { path: "{{ downloads_dir }}", group: "data", mode: "ug=rwx,o=rx" }
    - { path: "{{ deluge_completed_dir }}", group: "data", mode: "ug=rwx,o=rx" }
    - { path: "{{ deluge_downloads_dir }}", group: "data", mode: "ug=rwx,o=rx" }
    - { path: "{{ jackett_downloads_dir }}", group: "data", mode: "ug=rwx,o=rx" }
    - { path: "{{ jellyfin_config_dir }}", mode: "u=rwx,g=rx,o=" }
    - { path: "{{ jellyfin_transcode_dir }}" }
    - { path: "{{ minecraft_data_dir }}" }
    - { path: "{{ minecraft_map_dir }}", group: "data", mode: "ug=rwx,o=rx" }
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "directory"
    recurse: no
    owner: "docker-appdata"
    group: "{{ item.group | default('docker-appdata', true) }}"
    mode: "{{ item.mode | default('ug=rwx,o=', true) }}"

- name: "Glances"
  include_role:
    name: "app.glances"
  vars:
    config_dir: "{{ docker_appdata_dir }}/glances"
    dest: "{{ docker_apps_dir }}/fragments/glances.service.yml"
    fragment_definition:
      labels:
        avatar.subdomain: "glances"
        traefik.docker.network: "glances"
      networks:
        glances: {}

- name: "Traefik"
  include_role:
    name: "app.traefik"
  vars:
    config_dir: "{{ docker_appdata_dir }}/traefik"
    dest: "{{ docker_apps_dir }}/fragments/traefik.service.yml"
    fragment_definition:
      labels:
        avatar.subdomain: "traefik"
      networks:
        public:
          ipv4_address: "{{ docker_ip_proxy }}"
        glances: {}
        media: {}
    traefik:
      domain: "{{ internal_hostname }}"
      trusted_ips: "{{ network.servers.automate.ip }}/32"

- name: "LEGACY: Copy docker images"
  ansible.builtin.copy:
    src: "docker-images"
    dest: "{{ docker_apps_dir }}"
    owner: "root"
    group: "docker"
    directory_mode: "ug=rwx,o="
    mode: "ug+rw,o=" # Preserve exec. bit where applicable

- name: "LEGACY: Copy god docker compose fragment"
  loop:
    - { path: "fragments/docker-compose.yml" }
    - { path: "jobs/docker-compose.yml" }
  ansible.builtin.template:
    src: "docker/{{ item.path }}.j2"
    dest: "{{ docker_apps_dir }}/{{ item.path }}"
    owner: "root"
    group: "docker"
    mode: "ug=rw,o="

- name: "Create docker-compose.yml"
  include_role:
    name: "app"
    tasks_from: "merge-fragments"
  vars:
    src: "{{ docker_apps_dir }}/fragments/"
    dest: "{{ docker_apps_dir }}/docker-compose.yml"

- name: "LEGACY: Copy initial app configs"
  ansible.builtin.unarchive:
    creates: "{{ docker_appdata_dir }}"
    src: "{{ appdata_archive }}"
    dest: "{{ docker_apps_dir }}"

- name: "LEGACY: Copy managed app configs"
  ansible.builtin.copy:
    src: "appdata/"
    dest: "{{ docker_appdata_dir }}"
    owner: "docker-appdata"
    group: "docker-appdata"
    directory_mode: "u=rwx,g=rx,o="
    mode: "u+rw,g+r-w,o=" # Preserve exec. bit where applicable

- name: "Cleanup old files"
  loop:
    - { path: "{{ docker_appdata_dir }}/traefik.toml" }
    - { path: "{{ docker_appdata_dir }}/plex" }
    - { path: "{{ data_mount }}/plex" }
  ansible.builtin.file:
    state: "absent"
    path: "{{ item.path }}"
