- name: "Migrate docker-apps directory"
  notify: "cleanup"
  ansible.builtin.command:
    cmd: "mv /srv/docker {{ docker_apps_dir | quote }}"
    creates: "{{ docker_apps_dir }}"

- name: "Create docker directories"
  loop:
    - { path: "{{ docker_apps_dir }}" }
    - { path: "{{ docker_apps_dir }}/fragments" }
    - { path: "{{ docker_appdata_dir }}" }
    - { path: "{{ docker_apps_dir }}/jobs" }
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "directory"
    owner: "root"
    group: "docker"
    mode: 0770

- name: "LEGACY: Create data directories"
  loop:
    - { path: "{{ downloads_dir }}", owner: "root", group: "{{ download_group.name }}", mode: "750" }
    - { path: "{{ backups_dir }}" }
    - { path: "{{ appdata_backups_dir }}" }
    - { path: "{{ minecraft_backups_dir }}" }
    - { path: "{{ minecraft_data_dir }}" }
    - { path: "{{ minecraft_map_dir }}", group: "data", mode: "ug=rwx,o=rx" }
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "directory"
    recurse: no
    owner: "{{ item.owner | default('docker-appdata', true) }}"
    group: "{{ item.group | default('docker-appdata', true) }}"
    mode: "{{ item.mode | default('ug=rwx,o=', true) }}"

- name: "Create network fragments"
  loop:
    - { name: "public", subnet: "{{ docker_net_public }}" }
    - { name: "glances", subnet: "{{ docker_net_glances }}" }
    - { name: "media", subnet: "{{ docker_net_media }}" }
    - { name: "minecraft", subnet: "{{ docker_net_minecraft }}" }
  include_role:
    name: "app"
    tasks_from: "network-fragment"
  vars:
    dest: "{{ docker_apps_dir }}/fragments/{{ item.name }}.network.yml"
    fragment:
      name: "{{ item.name }}"
      definition:
        driver: "bridge"
        ipam:
          driver: "default"
          config:
            - subnet: "{{ item.subnet }}"

- name: "Deluge"
  include_role:
    name: "app.deluge"
  vars:
    dest: "{{ docker_apps_dir }}/fragments/deluge.service.yml"
    validate: false
    deluge:
      config_dir: "{{ docker_appdata_dir }}/deluge"
      blackhole_dir: "{{ downloads_dir }}/jackett"
      downloads_dir: "{{ downloads_dir }}/deluge"
      group: "{{ download_group.name }}"
      fragment:
        definition:
          depends_on: ["vpn"]
          network_mode: "service:vpn"
          labels:
            avatar.subdomain: "deluge"

- name: "Glances"
  include_role:
    name: "app.glances"
  vars:
    dest: "{{ docker_apps_dir }}/fragments/glances.service.yml"
    glances:
      fragment:
        definition:
          labels:
            avatar.subdomain: "glances"
            traefik.docker.network: "glances"
          networks:
            glances: {}

- name: "Jackett"
  include_role:
    name: "app.jackett"
  vars:
    dest: "{{ docker_apps_dir }}/fragments/jackett.service.yml"
    validate: false
    jackett:
      config_dir: "{{ docker_appdata_dir }}/jackett"
      downloads_dir: "{{ downloads_dir }}/jackett"
      group: "{{ download_group.name }}"
      fragment:
        definition:
          depends_on: ["vpn"]
          labels:
            avatar.subdomain: "jackett"
          network_mode: "service:vpn"

- name: "Jellyfin"
  include_role:
    name: "app.jellyfin"
  vars:
    dest: "{{ docker_apps_dir }}/fragments/jellyfin.service.yml"
    jellyfin:
      config_dir: "{{ docker_appdata_dir }}/jellyfin"
      transcode_dir: "{{ data_mount }}/jellyfin"
      series_dir: "{{ series_dir }}"
      movies_dir: "{{ movies_dir }}"
      extra_groups:
        - "{{ media_group }}"
      fragment:
        definition:
          labels:
            avatar.subdomain: "jellyfin"
            traefik.docker.network: "media"
          networks:
            media: {}

- name: "Radarr"
  include_role:
    name: "app.radarr"
  vars:
    dest: "{{ docker_apps_dir }}/fragments/radarr.service.yml"
    radarr:
      config_dir: "{{ docker_appdata_dir }}/radarr"
      downloads_dir: "{{ downloads_dir }}/deluge"
      movies_dir: "{{ movies_dir }}"
      movies_group: "{{ media_group.name }}"
      extra_groups:
        - "{{ download_group }}"
        - "{{ media_group }}"
      fragment:
        definition:
          labels:
            avatar.subdomain: "radarr"
            traefik.docker.network: "media"
          networks:
            media: {}

- name: "Sonarr"
  include_role:
    name: "app.sonarr"
  vars:
    dest: "{{ docker_apps_dir }}/fragments/sonarr.service.yml"
    sonarr:
      config_dir: "{{ docker_appdata_dir }}/sonarr"
      downloads_dir: "{{ downloads_dir }}/deluge"
      series_dir: "{{ series_dir }}"
      series_group: "{{ media_group.name }}"
      extra_groups:
        - "{{ download_group }}"
        - "{{ media_group }}"
      fragment:
        definition:
          labels:
            avatar.subdomain: "sonarr"
            traefik.docker.network: "media"
          networks:
            media: {}

- name: "Traefik"
  include_role:
    name: "app.traefik"
  vars:
    dest: "{{ docker_apps_dir }}/fragments/traefik.service.yml"
    traefik:
      config_dir: "{{ docker_appdata_dir }}/traefik"
      domain: "{{ internal_hostname }}"
      trusted_ips: "{{ network.servers.automate.ip }}/32"
      fragment:
        definition:
          labels:
            avatar.subdomain: "traefik"
          networks:
            public:
              ipv4_address: "{{ docker_ip_proxy }}"
            glances: { }
            media: { }

- name: "VPN"
  include_role:
    name: "app.vpn"
  vars:
    dest: "{{ docker_apps_dir }}/fragments/vpn.service.yml"
    vpn:
      config_file: "CA-Montreal_UDP.ovpn"
      forwarding_port: "{{ deluge_incoming_port }}"
      username: "{{ cryptostorm_username }}"
      fragment:
        definition:
          networks:
            media: {}
            public: {}

- name: "LEGACY: Copy docker images"
  ansible.builtin.copy:
    src: "docker-images"
    dest: "{{ docker_apps_dir }}"
    owner: "root"
    group: "docker"
    directory_mode: "ug=rwx,o="
    mode: "ug+rw,o=" # Preserve exec. bit where applicable

- name: "LEGACY: Copy god docker compose fragment"
  loop:
    - { path: "fragments/docker-compose.yml" }
    - { path: "jobs/docker-compose.yml" }
  ansible.builtin.template:
    src: "docker/{{ item.path }}.j2"
    dest: "{{ docker_apps_dir }}/{{ item.path }}"
    owner: "root"
    group: "docker"
    mode: "ug=rw,o="

- name: "Create docker-compose.yml"
  include_role:
    name: "app"
    tasks_from: "merge-fragments"
  vars:
    src: "{{ docker_apps_dir }}/fragments/"
    dest: "{{ docker_apps_dir }}/docker-compose.yml"

- name: "LEGACY: Copy initial app configs"
  ansible.builtin.unarchive:
    creates: "{{ docker_appdata_dir }}"
    src: "{{ appdata_archive }}"
    dest: "{{ docker_apps_dir }}"

- name: "LEGACY: Copy managed app configs"
  ansible.builtin.copy:
    src: "appdata/"
    dest: "{{ docker_appdata_dir }}"
    owner: "docker-appdata"
    group: "docker-appdata"
    directory_mode: "u=rwx,g=rx,o="
    mode: "u+rw,g+r-w,o=" # Preserve exec. bit where applicable
