- name: "Create app directories"
  loop:
    - { path: "{{ media_apps_dir }}" }
    - { path: "{{ media_fragments_dir }}" }
    - { path: "{{ media_appdata_dir }}" }
    - { path: "{{ media_apps_dir }}/jobs" }
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "directory"
    owner: "root"
    group: "docker"
    mode: 0750

- name: "LEGACY: Create data directories"
  loop:
    - { path: "{{ minecraft_backups_dir }}", owner: "docker-appdata", group: "docker-appdata" }
    - { path: "{{ minecraft_data_dir }}", owner: "docker-appdata", group: "docker-appdata" }
    - { path: "{{ minecraft_map_dir }}", owner: "docker-appdata", group: "data", mode: "775" }
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "directory"
    recurse: false
    owner: "{{ item.owner | default('root', true) }}"
    group: "{{ item.group | default('root', true) }}"
    mode: "{{ item.mode | default('770', true) }}"

- name: "Create network fragments"
  loop:
    - { name: "public", subnet: "{{ docker_net_public }}" }
    - { name: "glances", subnet: "{{ docker_net_glances }}" }
    - { name: "media", subnet: "{{ docker_net_media }}" }
    - { name: "minecraft", subnet: "{{ docker_net_minecraft }}" }
  include_role:
    name: "app"
    tasks_from: "network-fragment"
  vars:
    dest: "{{ media_fragments_dir }}/{{ item.name }}.network.yml"
    fragment:
      name: "{{ item.name }}"
      definition:
        driver: "bridge"
        ipam:
          driver: "default"
          config:
            - subnet: "{{ item.subnet }}"

- name: "Deluge"
  include_role:
    name: "app.deluge"
  vars:
    dest: "{{ media_fragments_dir }}/deluge.service.yml"
    validate: false
    deluge:
      config_dir: "{{ media_appdata_dir }}/deluge"
      blackhole_dir: "{{ downloads_dir }}/jackett"
      downloads_dir: "{{ downloads_dir }}/deluge"
      group: "{{ download_group.name }}"
      fragment:
        definition:
          depends_on: ["vpn"]
          network_mode: "service:vpn"
          labels:
            avatar.subdomain: "deluge"

- name: "Glances"
  include_role:
    name: "app.glances"
  vars:
    dest: "{{ media_fragments_dir }}/glances.service.yml"
    glances:
      fragment:
        definition:
          labels:
            avatar.subdomain: "glances"
            traefik.docker.network: "glances"
          networks:
            glances: {}

- name: "Jackett"
  include_role:
    name: "app.jackett"
  vars:
    dest: "{{ media_fragments_dir }}/jackett.service.yml"
    validate: false
    jackett:
      config_dir: "{{ media_appdata_dir }}/jackett"
      downloads_dir: "{{ downloads_dir }}/jackett"
      group: "{{ download_group.name }}"
      fragment:
        definition:
          depends_on: ["vpn"]
          labels:
            avatar.subdomain: "jackett"
          network_mode: "service:vpn"

- name: "Jellyfin"
  include_role:
    name: "app.jellyfin"
  vars:
    dest: "{{ media_fragments_dir }}/jellyfin.service.yml"
    jellyfin:
      config_dir: "{{ media_appdata_dir }}/jellyfin"
      transcode_dir: "{{ data_mount }}/jellyfin"
      series_dir: "{{ series_dir }}"
      movies_dir: "{{ movies_dir }}"
      extra_groups:
        - "{{ media_group }}"
      fragment:
        definition:
          labels:
            avatar.subdomain: "jellyfin"
            traefik.docker.network: "media"
          networks:
            media: {}

- name: "Radarr"
  include_role:
    name: "app.radarr"
  vars:
    dest: "{{ media_fragments_dir }}/radarr.service.yml"
    radarr:
      config_dir: "{{ media_appdata_dir }}/radarr"
      downloads_dir: "{{ downloads_dir }}/deluge"
      movies_dir: "{{ movies_dir }}"
      movies_group: "{{ media_group.name }}"
      extra_groups:
        - "{{ download_group }}"
        - "{{ media_group }}"
      fragment:
        definition:
          labels:
            avatar.subdomain: "radarr"
            traefik.docker.network: "media"
          networks:
            media: {}

- name: "Sonarr"
  include_role:
    name: "app.sonarr"
  vars:
    dest: "{{ media_fragments_dir }}/sonarr.service.yml"
    sonarr:
      config_dir: "{{ media_appdata_dir }}/sonarr"
      downloads_dir: "{{ downloads_dir }}/deluge"
      series_dir: "{{ series_dir }}"
      series_group: "{{ media_group.name }}"
      extra_groups:
        - "{{ download_group }}"
        - "{{ media_group }}"
      fragment:
        definition:
          labels:
            avatar.subdomain: "sonarr"
            traefik.docker.network: "media"
          networks:
            media: {}

- name: "Traefik"
  include_role:
    name: "app.traefik"
  vars:
    dest: "{{ media_fragments_dir }}/traefik.service.yml"
    traefik:
      config_dir: "{{ media_appdata_dir }}/traefik"
      domain: "{{ internal_hostname }}"
      trusted_ips: "{{ network.servers.automate.ip }}/32"
      fragment:
        definition:
          labels:
            avatar.subdomain: "traefik"
          networks:
            public:
              ipv4_address: "{{ docker_ip_proxy }}"
            glances: {}
            media: {}

- name: "VPN"
  include_role:
    name: "app.vpn"
  vars:
    dest: "{{ media_fragments_dir }}/vpn.service.yml"
    vpn:
      config_file: "CA-Montreal_UDP.ovpn"
      forwarding_port: "{{ deluge_incoming_port }}"
      username: "{{ cryptostorm_username }}"
      fragment:
        definition:
          networks:
            media: {}
            public: {}

- block:
    - name: "List appdata backup exclusions"
      # This is a workaround until https://github.com/ansible/ansible/issues/10374 is fixed
      ansible.builtin.set_fact:
        media_appdata_exclusions: "{{ lookup('file', 'media/appdata_backup/exclusions.txt').split() }}"
    - name: "Appdata Backup"
      include_role:
        name: "app.tar-backup"
      vars:
        dest: "{{ media_fragments_dir }}/appdata-backup.service.yml"
        tar_backup:
          backup_dir: "{{ media_appdata_backup_dir }}"
          config_dir: "{{ media_appdata_dir }}/appdata-backup"
          data_dir: "{{ media_appdata_dir }}"
          crontab: "30 3 * * *"
          exclusions: "{{ media_appdata_exclusions }}"
          pause_containers: ["deluge", "jackett", "jellyfin", "radarr", "sonarr"]
          fragment:
            name: "media_appdata_backup"

- name: "LEGACY: Copy docker images"
  ansible.builtin.copy:
    src: "docker-images"
    dest: "{{ media_apps_dir }}"
    owner: "root"
    group: "docker"
    directory_mode: 0770
    mode: "ug+rw,o="

- name: "LEGACY: Copy god docker compose fragment"
  loop:
    - { path: "fragments/docker-compose.yml" }
    - { path: "jobs/docker-compose.yml" }
  ansible.builtin.template:
    src: "docker/{{ item.path }}.j2"
    dest: "{{ media_apps_dir }}/{{ item.path }}"
    owner: "root"
    group: "docker"
    mode: 0640

- name: "Create docker-compose.yml"
  include_role:
    name: "app"
    tasks_from: "merge-fragments"
  vars:
    src: "{{ media_fragments_dir }}/"
    dest: "{{ media_apps_dir }}/docker-compose.yml"

- name: "Copy last appdata backup"
  ansible.builtin.unarchive:
    creates: "{{ media_appdata_dir }}"
    src: "{{ appdata_archive }}"
    dest: "{{ media_apps_dir }}"

- name: "LEGACY: Copy managed app configs"
  ansible.builtin.copy:
    src: "appdata/"
    dest: "{{ media_appdata_dir }}"
    owner: "root"
    group: "docker"
    directory_mode: 0750
    mode: "u+rw,g+r-w,o="
