- name: Install ethernet tools
  pacman:
    name: "ethtool"
    state: "present"

- name: Copy WOL config
  template:
    src: "etc/systemd/network/15-wired.link.j2"
    dest: "/etc/systemd/network/15-wired.link"
    force: yes
    owner: "root"
    group: "root"
    mode: 0644
  notify: activate wol

- name: Copy NFTables configuration
  template:
    src: "etc/nftables.conf.j2"
    dest: "/etc/nftables.conf"
    force: yes
    owner: "root"
    group: "root"
    mode: 0600
    validate: 'nft -c -f %s'
  notify: reload nftables

- name: Enable NFTables
  systemd:
    name: "nftables.service"
    state: "started"
    enabled: yes
