- name: Install ethernet tools
  community.general.pacman:
    name:
      - ethtool
    state: "present"

- name: Copy WOL config
  ansible.builtin.template:
    src: "etc/systemd/network/15-wired.link.j2"
    dest: "/etc/systemd/network/15-wired.link"
    force: yes
    owner: "root"
    group: "root"
    mode: 0644
  notify: activate wol
