- name: Create system groups
  group:
    name: '{{ item.name }}'
    gid: '{{ item.gid }}'
    state: present
  loop:
    - { name: &data_group 'data', gid: '{{ system_data_gid }}' }
    - { name: &media_group 'media', gid: '{{ system_media_gid }}' }
    - { name: &appdata 'docker-appdata', gid: '{{ system_appdata_gid }}' }

- name: Create system users
  user:
    name: *appdata
    group: *appdata
    groups:
      - *data_group
      - *media_group
    uid: '{{ system_appdata_uid }}'
    create_home: no
    shell: '/usr/bin/nologin'
    state: present
