- name: Create system groups
  loop:
    - { name: "{{ media_group.name }}", gid: "{{ media_group.gid }}" }
    - { name: &data_group "data", gid: "{{ system_data_gid }}" }
    - { name: &appdata "docker-appdata", gid: "{{ system_appdata_gid }}" }
  ansible.builtin.group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: present

- name: Create system users
  ansible.builtin.user:
    name: *appdata
    group: *appdata
    groups:
      - *data_group
      - "{{ media_group.name }}"
    uid: "{{ system_appdata_uid }}"
    create_home: no
    shell: "/usr/bin/nologin"
    state: present
