- name: "Create system groups"
  loop:
    - { name: "{{ download_group.name }}", gid: "{{ download_group.gid }}" }
    - { name: "{{ media_group.name }}", gid: "{{ media_group.gid }}" }
    - { name: &data_group "data", gid: "{{ system_data_gid }}" }
    - { name: &appdata "docker-appdata", gid: "{{ system_appdata_gid }}" }
  ansible.builtin.group:
    gid: "{{ item.gid }}"
    name: "{{ item.name }}"
    state: "present"
    system: true

- name: "Create system users"
  ansible.builtin.user:
    name: *appdata
    group: *appdata
    groups:
      - *data_group
      - "{{ media_group.name }}"
    uid: "{{ system_appdata_uid }}"
    create_home: false
    shell: "/usr/bin/nologin"
    state: "present"
    system: true
